version: '3.9'
services:
  postgresql:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER : elwan
      POSTGRES_PASSWORD: elwan
      POSTGRES_DB: IOT


  fast-api:
    build: .
    ports:
      - '80:80'
    volumes:
      - ./logs:/logs
    depends_on: ["postgresql"]

  discord-bot:
    build:
      context: .
      dockerfile: "Dockerfile-bot"
    volumes:
      - ./logs:/logs
    depends_on: ["fast-api"]
