FROM python:3.11


WORKDIR /code

COPY ./requirements.txt /code/requirements.txt
COPY ./config.json /code/config.json

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./discord_bot_iot.py /code/discord_bot_iot.py

CMD ["python", "discord_bot_iot.py"]
